print("--**--**--Calculator--**--**--")
print ("1.Add\n2.Sub\n3.Mul\n4.Div")
n=int(input("Enter your choice:"))
a=int(input("Enter num1:"))
b=int(input("Enter num2:"))
if(n==1):print("Sum is ",a+b)
if(n==2):print("diff is",a-b)
if(n==3):print("product is",a*b)
if(n==4):print('qoutient is ',a/b)
